<a href="https://colab.research.google.com/github/financieras/big_data/blob/main/retos/reto_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Reto 2. Carga directa desde URL y an√°lisis exploratorio**
- Carga Titanic desde URL con Pandas
- Verifica con `.shape` y `.head()`
- Explora tipos de datos con `.dtypes`, valores nulos con `.isnull().sum()` y estad√≠sticas descriptivas con `.describe()`

# **Resoluci√≥n del Reto 2**

## **Paso 1: Cargar dataset Titanic desde URL**
Para la descarga del Dataset se elige la web de **DataScienceDojo**. Motivos:
- Es una Organizaci√≥n educativa reconocida en data science
- GitHub raw: Formato directo para pandas (pd.read_csv)
- Estabilidad: URL activa por a√±os, muy confiable
- Formato limpio: Dataset listo para usar sin preprocesamiento

In [1]:
# EJECUTA ESTE C√ìDIGO PARA CARGAR DESDE URL
import pandas as pd
import numpy as np

print("üåê Paso 1: Cargando dataset Titanic desde URL...")
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("‚úÖ Dataset cargado correctamente desde URL")

üåê Paso 1: Cargando dataset Titanic desde URL...
‚úÖ Dataset cargado correctamente desde URL

## **Paso 2: Verificar dimensiones y primeras filas**
`df.shape` devuelve la tupla (891, 12) lo que indica que el Dataset tiene:
- 891 filas
- 12 columnas.

In [2]:
# EJECUTA ESTE C√ìDIGO PARA VERIFICAR DATOS
print("üìè Paso 2: Verificando dimensiones del dataset...")
print(f"Dimensiones del dataset: {df.shape}")
print(f"- Filas: {df.shape[0]}")
print(f"- Columnas: {df.shape[1]}")

print("\nüëÄ Primeras 5 filas del dataset:")
df.head()

üìè Paso 2: Verificando dimensiones del dataset...
Dimensiones del dataset: (891, 12)
- Filas: 891
- Columnas: 12

üëÄ Primeras 5 filas del dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **Paso 3: Explorar tipos de datos**

In [5]:
# EJECUTAR ESTE C√ìDIGO PARA VER TIPOS DE DATOS
print("üîç Paso 3: Explorando tipos de datos...")
print("Tipos de datos por columna:")
print(df.dtypes)

print("\nüìä Resumen de tipos de datos:")
print(f"- Columnas num√©ricas: {len(df.select_dtypes(include=[np.number]).columns)}")
print(f"- Columnas categ√≥ricas: {len(df.select_dtypes(include=['object']).columns)}")

üîç Paso 3: Explorando tipos de datos...
Tipos de datos por columna:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

üìä Resumen de tipos de datos:
- Columnas num√©ricas: 7
- Columnas categ√≥ricas: 5

## **Paso 4: Identificar valores nulos**

In [6]:
# EJECUTAR ESTE C√ìDIGO PARA VALORES NULOS
print("‚ùì Paso 4: Identificando valores nulos...")
valores_nulos = df.isnull().sum()
print("Valores nulos por columna:")
print(valores_nulos)

print(f"\nüìà Total de valores nulos en el dataset: {df.isnull().sum().sum()}")
print(f"üìä Porcentaje de valores nulos: {(df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100):.2f}%")

# Columnas con valores nulos
columnas_con_nulos = valores_nulos[valores_nulos > 0]
print(f"\nüö® Columnas con valores nulos: {len(columnas_con_nulos)}")
for columna, nulos in columnas_con_nulos.items():
    print(f"   - {columna}: {nulos} nulos ({nulos/df.shape[0]*100:.1f}%)")

‚ùì Paso 4: Identificando valores nulos...
Valores nulos por columna:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

üìà Total de valores nulos en el dataset: 866
üìä Porcentaje de valores nulos: 8.10%

üö® Columnas con valores nulos: 3
   - Age: 177 nulos (19.9%)
   - Cabin: 687 nulos (77.1%)
   - Embarked: 2 nulos (0.2%)

## **Paso 5: Estad√≠sticas descriptivas**

In [10]:
# EJECUTA ESTE C√ìDIGO PARA ESTAD√çSTICAS DESCRIPTIVAS
print("üìä Paso 5: Estad√≠sticas descriptivas...")

print("üî¢ Estad√≠sticas para variables num√©ricas:")
df.describe()

üìä Paso 5: Estad√≠sticas descriptivas...
üî¢ Estad√≠sticas para variables num√©ricas:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
print("\nüìù Estad√≠sticas para variables categ√≥ricas:")
df.describe(include=['object'])

üìù Estad√≠sticas para variables categ√≥ricas:

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

## **Paso 6: An√°lisis exploratorio adicional**

In [12]:
# EJECUTA ESTE C√ìDIGO PARA AN√ÅLISIS ADICIONAL
print("üéØ Paso 6: An√°lisis exploratorio adicional...")

# Informaci√≥n general del dataset
print("üìã Informaci√≥n general del dataset:")
df.info()

# Valores √∫nicos por columna categ√≥rica
print("\nüé≤ Valores √∫nicos en columnas categ√≥ricas:")
categoricas = df.select_dtypes(include=['object']).columns
for col in categoricas:
    print(f"   - {col}: {df[col].nunique()} valores √∫nicos")
    if df[col].nunique() <= 10:  # Mostrar valores si son pocos
        print(f"     Valores: {list(df[col].unique())}")

üéØ Paso 6: An√°lisis exploratorio adicional...
üìã Informaci√≥n general del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

üé≤ Valores √∫nicos en columnas categ√≥ricas:
   - Name: 891 valores √∫nicos
   - Sex: 2 valores √∫nicos
     Valores: ['male', 'female']
   - Ticket: 681 valores √∫nicos
   - Cabin: 147 valores √∫nicos
   - Embarked: 3 valores √∫nicos
     Valores: ['S', 'C', 'Q', nan]

## **Paso 7: Resumen ejecutivo del an√°lisis**

In [13]:
# EJECUTA ESTE C√ìDIGO PARA RESUMEN EJECUTIVO
print("üìà Paso 7: Resumen ejecutivo del an√°lisis exploratorio")

print("\n" + "="*50)
print("         RESUMEN EJECUTIVO - DATASET TITANIC")
print("="*50)

print(f"üìä DIMENSIONES: {df.shape[0]} pasajeros √ó {df.shape[1]} caracter√≠sticas")

print(f"üîç TIPOS DE DATOS:")
print(f"   - Num√©ricas: {len(df.select_dtypes(include=[np.number]).columns)} columnas")
print(f"   - Categ√≥ricas: {len(df.select_dtypes(include=['object']).columns)} columnas")

nulos_totales = df.isnull().sum().sum()
print(f"‚ùì VALORES NULOS: {nulos_totales} ({nulos_totales/(df.shape[0]*df.shape[1])*100:.1f}% del dataset)")

# Principales hallazgos
print(f"üéØ PRINCIPALES HALLAZGOS:")
print(f"   - Tasa de supervivencia: {df['Survived'].mean()*100:.1f}%")
print(f"   - Edad promedio: {df['Age'].mean():.1f} a√±os")
print(f"   - Tarifa promedio: ${df['Fare'].mean():.2f}")

print(f"\n‚úÖ Columnas disponibles:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col}")

print("\nüéâ ¬°Reto 2 completado! An√°lisis exploratorio finalizado")
print("="*50)

üìà Paso 7: Resumen ejecutivo del an√°lisis exploratorio

==================================================
         RESUMEN EJECUTIVO - DATASET TITANIC
==================================================
üìä DIMENSIONES: 891 pasajeros √ó 12 caracter√≠sticas
üîç TIPOS DE DATOS:
   - Num√©ricas: 7 columnas
   - Categ√≥ricas: 5 columnas
‚ùì VALORES NULOS: 866 (8.1% del dataset)
üéØ PRINCIPALES HALLAZGOS:
   - Tasa de supervivencia: 38.4%
   - Edad promedio: 29.7 a√±os
   - Tarifa promedio: $32.20

‚úÖ Columnas disponibles:
    1. PassengerId
    2. Survived
    3. Pclass
    4. Name
    5. Sex
    6. Age
    7. SibSp
    8. Parch
    9. Ticket
   10. Fare
   11. Cabin
   12. Embarked

üéâ ¬°Reto 2 completado! An√°lisis exploratorio finalizado
==================================================

## **üéØ Puntos clave del Reto 2**

1. **Carga desde URL**: M√°s eficiente que subir archivos manualmente
2. **Dimensiones**: Entender el tama√±o del dataset
3. **Tipos de datos**: Fundamental para an√°lisis posteriores
4. **Valores nulos**: Identificar problemas de calidad de datos
5. **Estad√≠sticas descriptivas**: Primer vistazo a la distribuci√≥n de los datos
6. **Resumen ejecutivo**: Sintetizar hallazgos importantes

**üìö Valor educativo**: Este reto ense√±a las operaciones b√°sicas del EDA (Exploratory Data Analysis) que todo data scientist utiliza en sus primeros pasos con cualquier dataset nuevo.